# Configuring Rustfmt: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
comment_width = 120
condense_wildcard_suffixes = true
edition = "2021"
format_macro_matchers = true
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
overflow_delimited_expr = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
