[package]
name = "rust-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.56"
chrono = { version = "0.4" }
diesel = { version = "1.4", features = ["mysql", "r2d2", "postgres"] }
itertools = "0.10"
flexi_logger = { version = "0.22" }
log = "0.4"
scheduled-thread-pool = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-sdk = "1.10"
strum = "0.21"
strum_macros = "0.21"
thiserror = "1.0"
