[package]
name = "rust-utils"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.56"
borsh = "0.9.3"
chrono = { version = "0.4" }
config = { version = "0.13", features = ["toml"] }
diesel = { version = "1.4", features = ["mysql", "r2d2"], optional = true  }
flexi_logger = { version = "0.22" }
itertools = "0.10"
log = { version = "0.4", features = ["kv_unstable", "kv_unstable_serde"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
scheduled-thread-pool = { version = "0.2", optional = true }
sentry = "0.26.0"
sentry-log = "0.26.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-client = "1.10"
solana-sdk = "1.10"
strum = "0.21"
strum_macros = "0.21"
thiserror = "1.0"


[features]
db = [ "diesel", "scheduled-thread-pool" ]
default = []

[dev-dependencies]
claim = "0.5.0"
tokio = { version = "1.17", features = ["macros"] }
