[package]
edition = "2021"
name = "rust-utils"
version = "0.5.0"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = { version = "1.0.56", optional = true }
borsh = { version = "0.9.3", optional = true }
bs58 = { version="0.4.0", optional = true }
chrono = { version = "0.4", optional = true }
config = { version = "0.13", features = ["toml"], optional = true }
diesel = { version = "1.4", features = ["mysql", "r2d2"], optional = true }
ed25519-dalek = { version = "1.0.1", optional = true }
flexi_logger = { version = "0.22", optional = true }
jsonrpsee = { version = "0.15.1", features = ["http-server", "http-client"], optional = true }
log = { version = "0.4", features = [
  "kv_unstable",
  "kv_unstable_serde",
], optional = true }
opentelemetry = { version = "0.18", features = ["rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.17", features = ["rt-tokio", "reqwest_collector_client"], optional = true }
paste =  { version = "1", optional = true }
rand =  { version = "0.7", optional = true }
reqwest = { version = "0.11", features = ["blocking", "json"], optional = true }
scheduled-thread-pool = { version = "0.2", optional = true }
sentry = { version = "0.26.0", optional = true }
sentry-log = { version = "0.26.0", optional = true }
sentry-tracing = { version = "0.27", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "1.12", optional = true }
solana-client = { version = "1.14", optional = true }
solana-sdk = { version = "1.14", optional = true }
strum = { version = "0.21", optional = true }
strum_macros = { version = "0.21", optional = true }
thiserror = { version = "1.0", optional = true }
tokio = { version = "1.17", features = ["full"], optional = true }
tracing = { version = "0.1", optional = true }
tracing-bunyan-formatter = { version = "0.3", optional = true  }
tracing-log = { version = "0.1", optional = true  }
tracing-opentelemetry = { version = "0.18", optional = true }
tracing-stackdriver = { version = "0.5", optional = true }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"], optional = true }

[dev-dependencies]
claim = "0.5.0"
lazy_static = "1.4.0"

[features]
db = ["diesel", "scheduled-thread-pool"]
default = []
error = ["strum", "strum_macros", "thiserror"]
logger = ["sentry", "sentry-log", "log", "flexi_logger", "anyhow", "chrono"]
macros = []
settings = ["config", "log", "serde_with", "paste", "thiserror" ]
tokens = ["error", "borsh", "solana-client", "solana-sdk", "reqwest", "anyhow", "log" ]
telemetry = ["tracing", "opentelemetry", "opentelemetry-jaeger", "tracing-opentelemetry", "tracing-subscriber", "tracing-bunyan-formatter", "tracing-log", "tracing-stackdriver", "sentry-tracing", "sentry"]
crypto = [ "ed25519-dalek", "borsh", "bs58", "rand" ]
server = [ "jsonrpsee", "tokio", "log" ]
